EXAMPLES = [
    # Produtivo
    ("Preciso de atualização sobre o processo #123, por favor envie o status.", 'Produtivo'),
    ("O sistema está apresentando erro ao gerar relatórios, preciso de ajuda.", 'Produtivo'),
    ("Envio arquivos solicitados em anexo.", 'Produtivo'),
    ("A reunião foi adiada para amanhã no mesmo horário. Não falte, é importante.", 'Produtivo'),
    ("Convocamos todos para a reunião da próxima semana.", 'Produtivo'),
    ("Favor revisar o documento em anexo até sexta-feira.", 'Produtivo'),
    ("Solicito atualização sobre a abertura da conta corporativa iniciada na semana passada.", 'Produtivo'),
    ("Poderiam me enviar o status da análise de crédito referente ao processo #45789?", 'Produtivo'),
    ("Encaminho em anexo o comprovante de pagamento do boleto vencido em 12/09.", 'Produtivo'),
    ("Favor revisar os relatórios financeiros do segundo trimestre.", 'Produtivo'),
    ("Preciso que a equipe confirme a reunião marcada para amanhã às 14h.", 'Produtivo'),
    ("Segue a planilha de fluxo de caixa atualizada.", 'Produtivo'),
    ("Solicito aprovação para a transferência internacional pendente.", 'Produtivo'),
    ("Favor atualizar o cadastro do cliente João Pereira.", 'Produtivo'),
    ("Preciso de retorno sobre a solicitação de estorno enviada na última sexta-feira.", 'Produtivo'),
    ("A auditoria solicitou cópia dos contratos de empréstimo ativos.", 'Produtivo'),
    ("Favor anexar ao sistema os comprovantes fiscais de agosto.", 'Produtivo'),
    ("Estou reenviando os documentos solicitados pela área de compliance.", 'Produtivo'),
    ("Preciso do parecer jurídico sobre a cláusula do contrato de financiamento.", 'Produtivo'),
    ("Encaminho a versão revisada do relatório de riscos.", 'Produtivo'),
    ("Solicitamos apoio para desbloquear o acesso ao sistema de gestão.", 'Produtivo'),
    ("Favor informar o saldo atualizado da conta investimento #99872.", 'Produtivo'),
    ("Necessário confirmar a liquidação da operação de câmbio de ontem.", 'Produtivo'),
    ("Encaminho proposta comercial revisada para análise.", 'Produtivo'),
    ("Favor incluir os novos dados bancários no cadastro do fornecedor.", 'Produtivo'),
    ("Preciso do cronograma atualizado para entrega do projeto X.", 'Produtivo'),
    ("Segue relatório consolidado das despesas do mês.", 'Produtivo'),
    ("Solicito a emissão da nota fiscal referente ao contrato Y.", 'Produtivo'),
    ("Encaminho documentação para abertura de conta PJ.", 'Produtivo'),
    ("Preciso confirmar o agendamento da videoconferência de amanhã.", 'Produtivo'),
    ("Solicito a reemissão do boleto da fatura de setembro.", 'Produtivo'),
    ("Favor encaminhar as informações de contato do responsável pela auditoria.", 'Produtivo'),
    ("Preciso de suporte para corrigir erro na conciliação bancária.", 'Produtivo'),
    ("Encaminho termo de adesão assinado digitalmente.", 'Produtivo'),
    ("Favor revisar os indicadores de performance enviados no dashboard.", 'Produtivo'),
    ("Solicito confirmação da atualização cadastral concluída no sistema.", 'Produtivo'),
    ("Preciso de atualização sobre a análise do contrato de crédito enviado ontem.", 'Produtivo'),
    ("Favor reenviar os relatórios trimestrais para o comitê.", 'Produtivo'),
    ("Solicito desbloqueio imediato da conta PJ #45678.", 'Produtivo'),
    ("Segue em anexo a planilha com as despesas do mês.", 'Produtivo'),
    ("Preciso da confirmação do pagamento da fatura #98231.", 'Produtivo'),
    ("Favor revisar os documentos enviados pelo cliente João Silva.", 'Produtivo'),
    ("Solicito posição sobre a auditoria externa programada para novembro.", 'Produtivo'),
    ("Encaminho os comprovantes fiscais pendentes para análise.", 'Produtivo'),
    ("Necessário confirmar a liquidação da operação de câmbio realizada ontem.", 'Produtivo'),
    ("Preciso de suporte para acesso ao sistema de relatórios.", 'Produtivo'),
    ("Favor revisar os indicadores de performance de setembro.", 'Produtivo'),
    ("Encaminho minuta revisada do contrato de parceria.", 'Produtivo'),
    ("Solicito confirmação da atualização cadastral do cliente.", 'Produtivo'),
    ("Favor agendar reunião com a área de compliance para sexta-feira.", 'Produtivo'),
    ("Preciso que a equipe envie o parecer jurídico até amanhã.", 'Produtivo'),
    ("Encaminho a planilha de fluxo de caixa revisada.", 'Produtivo'),
    ("Solicito aprovação da transferência internacional de 20 mil dólares.", 'Produtivo'),
    ("Preciso de retorno sobre a solicitação de estorno do boleto vencido.", 'Produtivo'),
    ("Favor anexar ao sistema os contratos digitalizados.", 'Produtivo'),
    ("Segue versão final do relatório de riscos corporativos.", 'Produtivo'),
    ("Solicito desbloqueio de acesso do colaborador ao ERP.", 'Produtivo'),
    ("Favor informar o saldo atualizado da conta investimento #12345.", 'Produtivo'),
    ("Encaminho proposta revisada para avaliação da diretoria.", 'Produtivo'),
    ("Preciso da ata da reunião de ontem para registro.", 'Produtivo'),
    ("Solicito emissão da nota fiscal do contrato #897.", 'Produtivo'),
    ("Favor incluir novos dados bancários do fornecedor XPTO.", 'Produtivo'),
    ("Segue relatório consolidado de despesas do trimestre.", 'Produtivo'),
    ("Preciso confirmar agendamento da videoconferência às 15h.", 'Produtivo'),
    ("Encaminho documentação para abertura de conta corrente empresarial.", 'Produtivo'),
    ("Solicito atualização do cronograma do projeto Finance X.", 'Produtivo'),
    ("Preciso de parecer contábil sobre a operação registrada ontem.", 'Produtivo'),
    ("Encaminho termo de adesão assinado eletronicamente.", 'Produtivo'),
    ("Solicito apoio da TI para corrigir erro de conciliação bancária.", 'Produtivo'),
    ("Favor revisar planilha de metas enviada pela área comercial.", 'Produtivo'),
    ("Encaminho comprovante de pagamento referente à fatura #789.", 'Produtivo'),
    ("Preciso que enviem relatório de inadimplência atualizado.", 'Produtivo'),
    ("Solicito aprovação para contratação do serviço externo.", 'Produtivo'),
    ("Favor confirmar recebimento dos documentos de compliance.", 'Produtivo'),
    ("Segue ata revisada da reunião de diretoria.", 'Produtivo'),
    ("Solicito status da análise de crédito do cliente Maria Souza.", 'Produtivo'),
    ("Preciso que revisem os indicadores financeiros de agosto.", 'Produtivo'),
    ("Encaminho contratos revisados para assinatura.", 'Produtivo'),
    ("Solicito inclusão de novo usuário no sistema de gestão.", 'Produtivo'),
    ("Favor enviar relatórios de performance semanal.", 'Produtivo'),
    ("Preciso da aprovação da diretoria para execução do projeto Y.", 'Produtivo'),
    ("Encaminho parecer jurídico solicitado ontem.", 'Produtivo'),
    ("Solicito revisão do processo #99873 no sistema.", 'Produtivo'),
    ("Favor atualizar cadastro do cliente Carlos Eduardo.", 'Produtivo'),
    ("Preciso confirmar a liquidação do contrato de câmbio #4578.", 'Produtivo'),
    ("Encaminho cronograma atualizado do projeto Finance Pro.", 'Produtivo'),
    ("Solicito emissão do boleto de outubro.", 'Produtivo'),
    ("Preciso de orientação sobre cláusula contratual.", 'Produtivo'),
    ("Favor revisar a planilha de riscos operacionais.", 'Produtivo'),
    ("Solicito a consolidação dos resultados financeiros do trimestre.", 'Produtivo'),
    ("Encaminho minuta de aditivo contratual.", 'Produtivo'),
    ("Preciso do relatório de conciliação de ontem.", 'Produtivo'),
    ("Solicito confirmação de recebimento da documentação enviada.", 'Produtivo'),
    ("Favor reemitir nota fiscal referente ao contrato #566.", 'Produtivo'),
    ("Segue documentação do cliente para validação.", 'Produtivo'),
    ("Preciso do detalhamento das despesas de setembro.", 'Produtivo'),
    ("Solicito revisão da política de crédito interna.", 'Produtivo'),
    ("Favor informar prazos de liquidação de operações internacionais.", 'Produtivo'),
    ("Encaminho planilha de contas a pagar atualizada.", 'Produtivo'),
    ("Solicito parecer sobre risco operacional identificado.", 'Produtivo'),
    ("Preciso de relatório consolidado de investimentos.", 'Produtivo'),
    ("Encaminho documentos solicitados pela auditoria externa.", 'Produtivo'),
    ("Favor revisar cálculo de provisão de inadimplência.", 'Produtivo'),
    ("Solicito atualização do sistema com dados de setembro.", 'Produtivo'),
    ("Preciso confirmar agenda de reunião com investidores.", 'Produtivo'),
    ("Encaminho comprovante de TED realizada hoje.", 'Produtivo'),
    ("Solicito aprovação do orçamento para o projeto Z.", 'Produtivo'),
    ("Favor incluir nota explicativa no relatório contábil.", 'Produtivo'),
    ("Preciso confirmar prazos de auditoria.", 'Produtivo'),
    ("Encaminho minuta de contrato revisada.", 'Produtivo'),
    ("Solicito backup do sistema de gestão financeira.", 'Produtivo'),
    ("Favor revisar dados de cadastro do fornecedor XP.", 'Produtivo'),
    ("Preciso do parecer da área fiscal.", 'Produtivo'),
    ("Encaminho ata de reunião para validação.", 'Produtivo'),
    ("Solicito atualização de senha no sistema.", 'Produtivo'),
    ("Favor confirmar recebimento do relatório enviado ontem.", 'Produtivo'),
    ("Preciso que enviem relatório sobre carteira de crédito.", 'Produtivo'),
    ("Encaminho material solicitado pela área de risco.", 'Produtivo'),
    ("Solicito alinhamento com a equipe de auditoria.", 'Produtivo'),
    ("Favor atualizar dados da conta PJ do cliente.", 'Produtivo'),
    ("Preciso confirmar a conclusão do processo cadastral.", 'Produtivo'),
    ("Encaminho proposta comercial finalizada.", 'Produtivo'),
    ("Solicito emissão de extrato consolidado.", 'Produtivo'),
    ("Favor revisar documentação fiscal enviada.", 'Produtivo'),
    ("Preciso do parecer jurídico sobre contrato social.", 'Produtivo'),
    ("Encaminho comprovante de quitação da fatura #112.", 'Produtivo'),
    ("Solicito relatório de riscos de mercado.", 'Produtivo'),
    ("Favor confirmar recebimento do aditivo contratual.", 'Produtivo'),
    ("Preciso da planilha de provisões contábeis atualizada.", 'Produtivo'),
    ("Encaminho dados para atualização no sistema ERP.", 'Produtivo'),
    ("Solicito posição sobre cobrança em aberto.", 'Produtivo'),
    ("Favor revisar relatórios da área de tesouraria.", 'Produtivo'),
    ("Gostaria de confirmar se a solicitação de abertura de conta corporativa enviada na semana passada já foi registrada no sistema e se existe algum prazo estimado para retorno.", "Produtivo"),
    ("Por favor, preciso do relatório detalhado das movimentações financeiras da filial de São Paulo referente ao último trimestre, incluindo entradas e saídas discriminadas.", "Produtivo"),
    ("Envio em anexo a documentação solicitada para dar continuidade ao processo de revisão contratual. Favor confirmar o recebimento.", "Produtivo"),
    ("Estamos enfrentando lentidão no sistema de conciliação bancária desde ontem à noite, dificultando o fechamento do balanço. Poderiam verificar a instabilidade?", "Produtivo"),
    ("Solicito atualização sobre o andamento do processo de auditoria interna. Precisamos dessa informação para o comitê da próxima segunda-feira.", "Produtivo"),
    ("Preciso da planilha com as taxas de câmbio utilizadas no fechamento de ontem para atualizar nossos relatórios internos.", "Produtivo"),
    ("A filial de Recife relatou falha no acesso ao sistema de cadastro de clientes. Podem nos informar se já há previsão de normalização?", "Produtivo"),
    ("Envio novamente o contrato revisado com as alterações solicitadas pela área jurídica. Por favor, validem se está em conformidade.", "Produtivo"),
    ("Gostaria de verificar se a transferência internacional enviada na terça-feira já foi processada e creditada na conta do beneficiário.", "Produtivo"),
    ("Solicito esclarecimentos sobre a divergência encontrada entre o relatório contábil e o extrato bancário de agosto.", "Produtivo"),
    ("Precisamos de uma segunda via da fatura referente ao serviço de custódia de ativos, pois a original não foi recebida pelo financeiro.", "Produtivo"),
    ("Encaminho o formulário assinado pelo cliente referente à abertura da linha de crédito. Confirmem se está completo ou se falta algum documento.", "Produtivo"),
    ("O sistema de aprovação de pagamentos está apresentando erro no momento da autenticação. Podem verificar com urgência?", "Produtivo"),
    ("Favor enviar a lista atualizada dos contratos de clientes que vencem no próximo mês para que possamos organizar as renovações.", "Produtivo"),
    ("Gostaria de confirmar se o pagamento do fornecedor XPTO foi processado corretamente, pois ainda não consta baixa no nosso sistema.", "Produtivo"),
    ("Encaminho as notas fiscais digitalizadas referentes ao mês de setembro, conforme solicitado pela área de compliance.", "Produtivo"),
    ("Solicito a atualização cadastral do cliente João Silva, CPF informado em anexo. O endereço precisa ser corrigido no sistema.", "Produtivo"),
    ("Preciso de acesso ao histórico de transações da conta nº 23456 desde janeiro para análise do setor de risco.", "Produtivo"),
    ("Estamos com dificuldades para acessar o portal de relatórios financeiros. Existe alguma manutenção programada?", "Produtivo"),
    ("Por gentileza, enviem o status da solicitação de desbloqueio da conta corporativa do cliente ABC Ltda.", "Produtivo"),
    ("Gostaria de solicitar a conciliação bancária referente à matriz, visto que há divergências com os dados do ERP.", "Produtivo"),
    ("Encaminho comprovante do pagamento realizado hoje cedo referente à cobrança pendente. Favor atualizar no sistema.", "Produtivo"),
    ("Solicitamos orientações sobre os procedimentos necessários para antecipação de recebíveis do cliente XPTO.", "Produtivo"),
    ("O relatório de risco de crédito de setembro não foi recebido. Podem reencaminhar?", "Produtivo"),
    ("Favor verificar a solicitação de aumento de limite de crédito feita pelo cliente há duas semanas, ainda sem retorno.", "Produtivo"),
    ("Envio comprovante de endereço atualizado do cliente Maria Souza para regularizar cadastro.", "Produtivo"),
    ("Há registros de duplicidade no lançamento das despesas operacionais. Podem corrigir os valores?", "Produtivo"),
    ("Solicito posição sobre o contrato de prestação de serviços que está em análise na área de compras.", "Produtivo"),
    ("Preciso do demonstrativo atualizado de aplicações financeiras da empresa, consolidado por filial.", "Produtivo"),
    ("Houve divergência entre o saldo informado no relatório diário e o extrato bancário. Favor verificar.", "Produtivo"),
    ("Encaminho em anexo a planilha de conciliação realizada internamente para validação de vocês.", "Produtivo"),
    ("Por favor, liberem o acesso ao novo colaborador no sistema de folha de pagamento.", "Produtivo"),
    ("Solicitamos prorrogação do prazo para envio de documentos relacionados ao processo de auditoria.", "Produtivo"),
    ("Favor confirmar se o pagamento agendado para amanhã já consta em programação no sistema.", "Produtivo"),
    ("Encaminho os relatórios gerenciais solicitados, por favor confirmem se atendem ao solicitado.", "Produtivo"),
    ("Estamos com dificuldades no upload de arquivos no portal. Existe limite de tamanho definido?", "Produtivo"),
    ("Solicito posição sobre a proposta comercial enviada na semana passada para o cliente XPTO.", "Produtivo"),
    ("Precisamos do manual atualizado do sistema de controle de acessos financeiros.", "Produtivo"),
    ("Houve atraso na compensação de boletos bancários de ontem. Qual a previsão de regularização?", "Produtivo"),
    ("Envio aqui a planilha de custos consolidada para validação e aprovação da área financeira.", "Produtivo"),
    ("Gostaria de confirmar se a solicitação de cartão corporativo já foi processada.", "Produtivo"),
    ("Por favor, encaminhem o laudo de auditoria que ficou pendente da última reunião.", "Produtivo"),
    ("Preciso do detalhamento das despesas com viagens corporativas referentes a setembro.", "Produtivo"),
    ("O cliente relatou bloqueio indevido em sua conta corrente. Podem analisar com urgência?", "Produtivo"),
    ("Encaminho contrato de prestação de serviços assinado digitalmente. Favor registrar no sistema.", "Produtivo"),
    ("Solicito relatório comparativo de investimentos entre os últimos três meses.", "Produtivo"),
    ("Estamos com dificuldade em aprovar pagamentos via módulo mobile. Podem verificar?", "Produtivo"),
    ("Favor enviar a lista atualizada dos clientes inadimplentes até o fechamento do mês passado.", "Produtivo"),
    ("Preciso confirmar se a operação de câmbio realizada ontem foi devidamente registrada.", "Produtivo"),
    ("Encaminho novamente a documentação do cliente, pois o envio anterior apresentou erro.", "Produtivo"),
    ("Solicitamos acesso à API de integração para automatizar os relatórios financeiros.", "Produtivo"),
    ("Gostaria de confirmar a data de vencimento do contrato firmado com a empresa XPTO.", "Produtivo"),
    ("Favor disponibilizar o histórico de crédito do cliente João Pedro para análise.", "Produtivo"),
    ("Precisamos atualizar o cadastro de fornecedores com os novos dados bancários.", "Produtivo"),
    ("Solicito apoio para configuração de usuários no sistema de aprovação de crédito.", "Produtivo"),
    ("Por favor, revisem a minuta do contrato que foi enviada para nossa avaliação.", "Produtivo"),
    ("Envio comprovante de pagamento de tarifas bancárias do mês passado para conferência.", "Produtivo"),
    ("Houve divergência no saldo da conta corrente da filial. Podem investigar?", "Produtivo"),
    ("Solicito autorização para movimentação de valores acima do limite padrão estabelecido.", "Produtivo"),
    ("Encaminho planilha de previsão orçamentária para revisão da área financeira.", "Produtivo"),
    ("Favor verificar se a fatura do fornecedor XPTO já consta como liquidada.", "Produtivo"),
    ("Gostaria de confirmar se a atualização cadastral do cliente foi processada.", "Produtivo"),
    ("Estamos aguardando retorno sobre a renegociação de contrato iniciada em agosto.", "Produtivo"),
    ("Envio em anexo a lista de colaboradores que necessitam de acesso ao sistema.", "Produtivo"),
    ("Solicito segunda via de boleto que não foi recebido pelo cliente até o vencimento.", "Produtivo"),
    ("Por favor, encaminhem a relação de contratos vencendo nos próximos 60 dias.", "Produtivo"),
    ("Houve inconsistência na geração do relatório financeiro de setembro. Favor corrigir.", "Produtivo"),
    ("Preciso de suporte para exportação de relatórios do sistema ERP.", "Produtivo"),
    ("Solicitamos confirmação de recebimento do dossiê de auditoria encaminhado ontem.", "Produtivo"),
    ("Envio o protocolo do chamado aberto para acompanhamento da resolução.", "Produtivo"),
    ("Gostaria de solicitar treinamento para novos usuários no sistema de crédito.", "Produtivo"),
    ("Encaminho minuta revisada do contrato coletivo para aprovação final.", "Produtivo"),
    ("Favor verificar o status da solicitação de desbloqueio de senha do gerente.", "Produtivo"),
    ("Precisamos da lista consolidada de inadimplência por segmento de cliente.", "Produtivo"),
    ("Por favor, enviem relatório detalhado das movimentações internacionais.", "Produtivo"),
    ("Encaminho documentos atualizados para conclusão do processo de auditoria.", "Produtivo"),
    ("Gostaria de confirmar se os valores pagos foram devidamente alocados em conta.", "Produtivo"),
    ("Solicito posição sobre a abertura de crédito especial solicitada pelo cliente.", "Produtivo"),
    ("Encaminho dados de acesso para integração do sistema externo com o banco.", "Produtivo"),
    ("Estamos com inconsistência nos saldos do sistema legado e do ERP atual.", "Produtivo"),
    ("Por favor, verifiquem se o contrato rescindido já consta como encerrado.", "Produtivo"),
    ("Envio comprovante de transferência internacional para registro contábil.", "Produtivo"),
    ("Solicito informações sobre garantias vinculadas aos contratos ativos.", "Produtivo"),
    ("Precisamos validar os lançamentos contábeis do mês anterior com urgência.", "Produtivo"),
    ("Gostaria de confirmar se os ajustes fiscais já foram aplicados no sistema.", "Produtivo"),
    ("Encaminho planilha de movimentações financeiras para conferência conjunta.", "Produtivo"),
    ("Favor enviar status do processo de abertura de filial solicitado em agosto.", "Produtivo"),
    ("Solicitamos relatório de fluxo de caixa consolidado até setembro.", "Produtivo"),
    ("Estamos enfrentando erro no módulo de aprovação de crédito desde ontem.", "Produtivo"),
    ("Envio em anexo contrato social atualizado do cliente para cadastro.", "Produtivo"),
    ("Preciso de suporte para migração de dados entre sistemas contábeis.", "Produtivo"),
    ("Favor verificar divergência apontada na auditoria referente a ativos.", "Produtivo"),
    ("Gostaria de solicitar cópia digital dos contratos firmados em 2023.", "Produtivo"),
    ("Encaminho novamente documentos que estavam ilegíveis no primeiro envio.", "Produtivo"),
    ("Solicito detalhamento das tarifas aplicadas nas operações recentes.", "Produtivo"),
    ("Estamos aguardando atualização sobre processo judicial vinculado a cliente.", "Produtivo"),
    ("Favor liberar acesso temporário para consultores externos ao sistema.", "Produtivo"),
    ("Envio relatório consolidado de investimentos para validação de vocês.", "Produtivo"),
    ("Gostaria de confirmar se a conciliação bancária do último mês foi finalizada.", "Produtivo"),
    ("Solicitamos posição sobre a alteração contratual encaminhada semana passada.", "Produtivo"),
    ("Preciso da base de dados atualizada de clientes ativos para revisão.", "Produtivo"),
    ("Encaminho carta de anuência assinada pelo cliente para quitação antecipada.", "Produtivo"),
    ("Por favor, disponibilizem extrato detalhado de aplicações financeiras.", "Produtivo"),
    ("Estamos com divergência entre saldo contábil e bancário desde ontem.", "Produtivo"),
    ("Envio documentação complementar para análise de crédito de cliente PJ.", "Produtivo"),
    ("Solicito atualização sobre andamento do contrato de prestação de serviços.", "Produtivo"),

    # Improdutivo
    ("Olá!", 'Improdutivo'),
    ("Oi!", 'Improdutivo'),
    ("As melhores coisas da vida são as mais simples.", 'Improdutivo'),
    ("Feliz Natal para toda equipe!", 'Improdutivo'),
    ("Obrigado pelo suporte, ótimo trabalho.", 'Improdutivo'),
    ("Parabéns pelo projeto, sucesso a todos.", 'Improdutivo'),
    ("Bom dia, espero que esteja bem!", 'Improdutivo'),
    ("Desejo um excelente final de semana a todos!", 'Improdutivo'),
    ("Feliz aniversário para todos os colegas que comemoram este mês!", 'Improdutivo'),
    ("Desejo um excelente final de semana para toda a equipe.", 'Improdutivo'),
    ("Bom dia! Espero que estejam todos bem.", 'Improdutivo'),
    ("Compartilho uma mensagem de motivação para iniciar a semana.", 'Improdutivo'),
    ("Feliz Natal e um próspero Ano Novo a todos.", 'Improdutivo'),
    ("Parabéns pelo sucesso do time no último evento.", 'Improdutivo'),
    ("Espero que todos aproveitem o feriado prolongado.", 'Improdutivo'),
    ("Compartilhando fotos do happy hour da semana passada.", 'Improdutivo'),
    ("Desejo uma ótima tarde a todos.", 'Improdutivo'),
    ("Envio este email apenas para agradecer pelo excelente trabalho.", 'Improdutivo'),
    ("Parabéns a todos os envolvidos no projeto concluído.", 'Improdutivo'),
    ("Que todos tenham uma semana produtiva e feliz.", 'Improdutivo'),
    ("Desejo uma ótima Páscoa para os colegas.", 'Improdutivo'),
    ("Compartilho artigo de revista sobre finanças pessoais.", 'Improdutivo'),
    ("Envio uma mensagem de agradecimento pela amizade no time.", 'Improdutivo'),
    ("Desejo sorte a todos os participantes da corrida de rua no domingo.", 'Improdutivo'),
    ("Que todos aproveitem bem o dia de sol.", 'Improdutivo'),
    ("Mensagem de bom humor para alegrar a semana.", 'Improdutivo'),
    ("Desejo uma boa viagem ao colega que está saindo de férias.", 'Improdutivo'),
    ("Compartilho um vídeo motivacional interessante.", 'Improdutivo'),
    ("Parabéns à equipe pelo aniversário de 10 anos da empresa.", 'Improdutivo'),
    ("Desejo felicidades aos aniversariantes de outubro.", 'Improdutivo'),
    ("Que todos tenham um ótimo almoço.", 'Improdutivo'),
    ("Compartilhando convite para confraternização de fim de ano.", 'Improdutivo'),
    ("Desejo que todos tenham um ótimo descanso no fim de semana.", 'Improdutivo'),
    ("Compartilho uma piada para animar a manhã.", 'Improdutivo'),
    ("Envio fotos do campeonato de futebol interno.", 'Improdutivo'),
    ("Parabéns pelo excelente clima organizacional alcançado.", 'Improdutivo'),
    ("Desejo a todos boas festas e muita saúde.", 'Improdutivo'),
    ("Apenas passando para cumprimentar todos os colegas.", 'Improdutivo'),
    ("Feliz Ano Novo a todos os colegas!", 'Improdutivo'),
    ("Bom dia! Desejo uma ótima terça-feira.", 'Improdutivo'),
    ("Parabéns pelo ótimo desempenho do time.", 'Improdutivo'),
    ("Espero que aproveitem o feriado prolongado.", 'Improdutivo'),
    ("Envio fotos do happy hour de sexta-feira.", 'Improdutivo'),
    ("Que todos tenham uma semana abençoada.", 'Improdutivo'),
    ("Desejo um excelente final de semana.", 'Improdutivo'),
    ("Parabéns pelo sucesso da festa de confraternização.", 'Improdutivo'),
    ("Compartilho um vídeo motivacional.", 'Improdutivo'),
    ("Bom almoço a todos!", 'Improdutivo'),
    ("Feliz aniversário ao colega João!", 'Improdutivo'),
    ("Desejo muita saúde e paz neste mês.", 'Improdutivo'),
    ("Mensagem de bom humor para alegrar o dia.", 'Improdutivo'),
    ("Parabéns à equipe pelos 20 anos da empresa.", 'Improdutivo'),
    ("Espero que aproveitem bem o dia de sol.", 'Improdutivo'),
    ("Desejo uma Páscoa feliz e cheia de alegria.", 'Improdutivo'),
    ("Compartilho artigo sobre saúde financeira pessoal.", 'Improdutivo'),
    ("Que todos tenham uma ótima tarde!", 'Improdutivo'),
    ("Envio mensagem apenas para agradecer.", 'Improdutivo'),
    ("Parabéns a todos os aniversariantes do mês.", 'Improdutivo'),
    ("Desejo uma ótima viagem ao colega que saiu de férias.", 'Improdutivo'),
    ("Compartilho piada para animar a manhã.", 'Improdutivo'),
    ("Que todos aproveitem o churrasco da sexta.", 'Improdutivo'),
    ("Parabéns pelo clima organizacional positivo.", 'Improdutivo'),
    ("Desejo boas festas e muita felicidade.", 'Improdutivo'),
    ("Bom descanso no feriado a todos.", 'Improdutivo'),
    ("Envio fotos do campeonato de futebol interno.", 'Improdutivo'),
    ("Compartilho mensagem motivacional sobre sucesso.", 'Improdutivo'),
    ("Desejo uma semana iluminada a todos.", 'Improdutivo'),
    ("Parabéns pelo resultado da corrida de rua.", 'Improdutivo'),
    ("Que todos tenham um excelente café da manhã.", 'Improdutivo'),
    ("Feliz Dia das Mães a todos!", 'Improdutivo'),
    ("Compartilho um convite para confraternização.", 'Improdutivo'),
    ("Desejo boa sorte na maratona do próximo domingo.", 'Improdutivo'),
    ("Mensagem de incentivo para a semana.", 'Improdutivo'),
    ("Parabéns pela apresentação no evento externo.", 'Improdutivo'),
    ("Desejo felicidade e harmonia para todos.", 'Improdutivo'),
    ("Bom feriado a todos, aproveitem!", 'Improdutivo'),
    ("Compartilho fotos da festa junina.", 'Improdutivo'),
    ("Desejo paz e sucesso para equipe.", 'Improdutivo'),
    ("Parabéns pelo prêmio recebido pela empresa.", 'Improdutivo'),
    ("Feliz aniversário à colega Maria!", 'Improdutivo'),
    ("Desejo alegria no início desta semana.", 'Improdutivo'),
    ("Envio poema motivacional para reflexão.", 'Improdutivo'),
    ("Parabéns pelo engajamento do time.", 'Improdutivo'),
    ("Bom descanso no fim de semana.", 'Improdutivo'),
    ("Desejo prosperidade a todos neste mês.", 'Improdutivo'),
    ("Feliz Natal e próspero Ano Novo.", 'Improdutivo'),
    ("Que todos aproveitem o feriado.", 'Improdutivo'),
    ("Compartilho vídeo engraçado para animar o dia.", 'Improdutivo'),
    ("Parabéns pelo sucesso no último evento social.", 'Improdutivo'),
    ("Desejo uma sexta-feira abençoada.", 'Improdutivo'),
    ("Bom dia! Apenas passando para cumprimentar.", 'Improdutivo'),
    ("Mensagem positiva para motivar a semana.", 'Improdutivo'),
    ("Parabéns pelo aniversário da empresa.", 'Improdutivo'),
    ("Desejo alegria no feriado prolongado.", 'Improdutivo'),
    ("Compartilho fotos da confraternização anual.", 'Improdutivo'),
    ("Bom final de semana a todos!", 'Improdutivo'),
    ("Desejo felicidade e paz no mês de outubro.", 'Improdutivo'),
    ("Parabéns ao colega pela promoção.", 'Improdutivo'),
    ("Espero que aproveitem o almoço de hoje.", 'Improdutivo'),
    ("Mensagem de amizade para equipe.", 'Improdutivo'),
    ("Desejo uma semana cheia de energia.", 'Improdutivo'),
    ("Feliz aniversário para todos do mês.", 'Improdutivo'),
    ("Compartilho artigo sobre finanças pessoais.", 'Improdutivo'),
    ("Bom dia, equipe! Que seja leve.", 'Improdutivo'),
    ("Parabéns pelo esforço coletivo no projeto.", 'Improdutivo'),
    ("Desejo ótima tarde de descanso.", 'Improdutivo'),
    ("Envio foto do time no café da manhã.", 'Improdutivo'),
    ("Mensagem motivadora para inspirar todos.", 'Improdutivo'),
    ("Desejo boa viagem ao colega.", 'Improdutivo'),
    ("Feliz aniversário à equipe da filial.", 'Improdutivo'),
    ("Bom humor para começar a semana.", 'Improdutivo'),
    ("Parabéns pela vitória do time interno.", 'Improdutivo'),
    ("Desejo um ótimo sábado ensolarado.", 'Improdutivo'),
    ("Envio imagens do passeio da empresa.", 'Improdutivo'),
    ("Mensagem de otimismo para hoje.", 'Improdutivo'),
    ("Desejo sucesso e saúde a todos.", 'Improdutivo'),
    ("Parabéns pelo ótimo trabalho do mês.", 'Improdutivo'),
    ("Feliz Dia dos Pais para todos.", 'Improdutivo'),
    ("Bom descanso merecido a todos.", 'Improdutivo'),
    ("Desejo uma semana produtiva.", 'Improdutivo'),
    ("Compartilho música motivacional.", 'Improdutivo'),
    ("Parabéns à equipe pelo engajamento.", 'Improdutivo'),
    ("Desejo excelente tarde de sol.", 'Improdutivo'),
    ("Envio fotos do time no evento esportivo.", 'Improdutivo'),
    ("Mensagem de gratidão ao grupo.", 'Improdutivo'),
    ("Desejo boas energias no mês novo.", 'Improdutivo'),
    ("Parabéns pelo sucesso no prêmio externo.", 'Improdutivo'),
    ("Bom dia! Que a semana seja ótima.", 'Improdutivo'),
    ("Desejo alegria na confraternização.", 'Improdutivo'),
    ("Compartilho lembrança do último evento social.", 'Improdutivo'),
    ("Parabéns pelos resultados do campeonato.", 'Improdutivo'),
    ("Desejo felicidade a todos sempre.", 'Improdutivo'),
    ("Bom dia, desejo a todos uma ótima semana de trabalho, cheia de conquistas e realizações!", "Improdutivo"),
    ("Queria compartilhar uma reflexão: a paciência é a chave para superar os desafios do dia a dia.", "Improdutivo"),
    ("Feliz aniversário para o colega João do departamento de TI, muitas felicidades!", "Improdutivo"),
    ("Desejo um excelente feriado prolongado a todos, aproveitem com a família.", "Improdutivo"),
    ("Parabéns à equipe pelo excelente trabalho na última campanha, estamos orgulhosos!", "Improdutivo"),
    ("Bom dia! Que a sexta-feira seja repleta de boas notícias e sorrisos.", "Improdutivo"),
    ("Compartilho com vocês uma frase motivacional: 'O sucesso é a soma de pequenos esforços repetidos dia após dia.'", "Improdutivo"),
    ("Gostaria de saber se teremos café da tarde especial hoje no escritório.", "Improdutivo"),
    ("Amanhã é o jogo decisivo do campeonato, quem vai assistir junto?", "Improdutivo"),
    ("Desejo boas férias ao colega Carlos, aproveite bastante esse merecido descanso.", "Improdutivo"),
    ("Bom dia a todos, lembrem-se de beber água e cuidar da saúde durante o expediente.", "Improdutivo"),
    ("Quero deixar registrado meu agradecimento pela amizade e parceria de todos vocês.", "Improdutivo"),
    ("Compartilho uma foto engraçada que recebi em um grupo, para alegrar a sexta-feira.", "Improdutivo"),
    ("Desejo uma excelente semana de muito sucesso para todos!", "Improdutivo"),
    ("Parabéns ao time de marketing pelo trabalho brilhante na última ação!", "Improdutivo"),
    ("Bom dia, pessoal! Hoje é dia de celebrar as pequenas vitórias do dia a dia.", "Improdutivo"),
    ("Compartilho com vocês uma curiosidade: vocês sabiam que o beija-flor pode bater as asas até 80 vezes por segundo?", "Improdutivo"),
    ("Desejo a todos um ótimo descanso no fim de semana que se aproxima.", "Improdutivo"),
    ("Quero agradecer à equipe pelo empenho, mesmo nos momentos mais difíceis.", "Improdutivo"),
    ("Alguém sabe se vai ter confraternização de fim de ano da empresa?", "Improdutivo"),
    ("Bom dia, que essa quarta-feira seja repleta de coisas boas para todos nós.", "Improdutivo"),
    ("Feliz Páscoa para toda equipe, que seja um momento de união e alegria.", "Improdutivo"),
    ("Gostaria de compartilhar uma música inspiradora que ouvi hoje cedo.", "Improdutivo"),
    ("Parabéns ao departamento financeiro pela organização do evento interno.", "Improdutivo"),
    ("Desejo sorte aos colegas que participarão da corrida de rua no domingo!", "Improdutivo"),
    ("Bom dia! Hoje é dia de agradecer pelas oportunidades que temos.", "Improdutivo"),
    ("Quero parabenizar a colega Maria pelo excelente trabalho no último relatório.", "Improdutivo"),
    ("Compartilho uma piada leve para animar a equipe no final do expediente.", "Improdutivo"),
    ("Desejo uma boa noite de descanso a todos, até amanhã.", "Improdutivo"),
    ("Boa tarde, gostaria de sugerir que façamos um amigo secreto de Natal.", "Improdutivo"),
    ("Parabéns à equipe de TI pelo esforço em manter o sistema sempre atualizado.", "Improdutivo"),
    ("Desejo uma ótima sexta-feira a todos, que seja produtiva e leve.", "Improdutivo"),
    ("Alguém sabe se haverá campanha de doação de sangue organizada pela empresa?", "Improdutivo"),
    ("Quero agradecer pelo apoio e companheirismo que recebo diariamente.", "Improdutivo"),
    ("Compartilho uma frase que me inspira: 'Nenhum obstáculo é grande demais quando temos determinação.'", "Improdutivo"),
    ("Bom dia a todos, espero que estejam animados para os desafios de hoje.", "Improdutivo"),
    ("Feliz Dia das Mães a todas as colaboradoras da empresa!", "Improdutivo"),
    ("Gostaria de saber se haverá festa junina organizada pelo RH este ano.", "Improdutivo"),
    ("Parabéns a todos que participaram do campeonato interno de futebol.", "Improdutivo"),
    ("Desejo que essa semana seja de muita paz e harmonia para todos.", "Improdutivo"),
    ("Boa noite, pessoal, até amanhã com novas energias!", "Improdutivo"),
    ("Quero compartilhar um artigo interessante sobre hábitos saudáveis no trabalho.", "Improdutivo"),
    ("Parabéns ao colega Paulo pelo nascimento de sua filha!", "Improdutivo"),
    ("Desejo um ótimo início de mês a todos, cheio de realizações.", "Improdutivo"),
    ("Alguém sabe se teremos ponto facultativo no próximo feriado?", "Improdutivo"),
    ("Bom dia, não esqueçam de sorrir, isso faz bem para a saúde!", "Improdutivo"),
    ("Feliz Dia dos Pais para todos que celebram essa data especial.", "Improdutivo"),
    ("Gostaria de compartilhar uma dica de leitura para o fim de semana.", "Improdutivo"),
    ("Parabéns ao time que participou da corrida corporativa!", "Improdutivo"),
    ("Desejo um excelente mês de dezembro a todos!", "Improdutivo"),
    ("Boa tarde, espero que estejam todos bem e animados.", "Improdutivo"),
    ("Compartilho aqui uma foto divertida do nosso mascote de escritório.", "Improdutivo"),
    ("Feliz Natal e um próspero Ano Novo a todos os colegas!", "Improdutivo"),
    ("Bom dia, que a energia positiva esteja presente em nossas tarefas.", "Improdutivo"),
    ("Quero agradecer pelas mensagens de apoio que recebi ontem.", "Improdutivo"),
    ("Parabéns ao setor de RH pela excelente organização da última campanha.", "Improdutivo"),
    ("Desejo que todos tenham uma ótima noite de descanso.", "Improdutivo"),
    ("Alguém sabe qual será o tema da festa de confraternização?", "Improdutivo"),
    ("Bom dia, que hoje possamos trabalhar com alegria e disposição.", "Improdutivo"),
    ("Compartilho um vídeo motivacional para inspirar nossa semana.", "Improdutivo"),
    ("Feliz Ano Novo a todos, que venha cheio de realizações!", "Improdutivo"),
    ("Desejo uma excelente terça-feira para toda a equipe.", "Improdutivo"),
    ("Boa tarde, gostaria de saber se haverá happy hour na sexta.", "Improdutivo"),
    ("Parabéns ao setor jurídico pela conquista recente.", "Improdutivo"),
    ("Desejo sucesso e realizações no projeto que se inicia hoje.", "Improdutivo"),
    ("Bom dia, compartilho uma mensagem de otimismo: 'Acredite no seu potencial.'", "Improdutivo"),
    ("Feliz dia da mulher a todas as colaboradoras!", "Improdutivo"),
    ("Quero saber quem está participando da corrida corporativa no próximo mês.", "Improdutivo"),
    ("Desejo que todos aproveitem bastante o feriado prolongado.", "Improdutivo"),
    ("Parabéns ao colega João por mais um ano de empresa!", "Improdutivo"),
    ("Boa tarde, compartilho um artigo sobre produtividade pessoal.", "Improdutivo"),
    ("Feliz aniversário à colega Ana, muitas felicidades!", "Improdutivo"),
    ("Desejo a todos uma semana iluminada.", "Improdutivo"),
    ("Bom dia, lembrem-se de que o sucesso é construído em equipe.", "Improdutivo"),
    ("Compartilho uma foto da confraternização do último ano.", "Improdutivo"),
    ("Parabéns pelo esforço coletivo no último trimestre!", "Improdutivo"),
    ("Desejo boas-vindas aos novos colaboradores da empresa.", "Improdutivo"),
    ("Boa noite, que amanhã seja ainda melhor para todos nós.", "Improdutivo"),
    ("Feliz sexta-feira! Que seja um dia de conquistas.", "Improdutivo"),
    ("Quero agradecer pelas mensagens de aniversário que recebi.", "Improdutivo"),
    ("Desejo uma ótima tarde a todos os colegas.", "Improdutivo"),
    ("Bom dia, compartilho aqui uma música para alegrar a equipe.", "Improdutivo"),
    ("Parabéns ao time de suporte pelo excelente atendimento.", "Improdutivo"),
    ("Desejo que todos tenham um ótimo descanso no fim do dia.", "Improdutivo"),
    ("Boa tarde, gostaria de indicar um filme para assistir no fim de semana.", "Improdutivo"),
    ("Feliz Dia do Trabalhador a todos os colaboradores!", "Improdutivo"),
    ("Quero compartilhar uma mensagem de otimismo com vocês.", "Improdutivo"),
    ("Desejo boas energias para todos no novo ciclo que se inicia.", "Improdutivo"),
    ("Bom dia! Hoje é um ótimo dia para novas oportunidades.", "Improdutivo"),
    ("Parabéns ao setor de inovação pela conquista do prêmio.", "Improdutivo"),
    ("Desejo sucesso aos colegas no novo projeto internacional.", "Improdutivo"),
    ("Boa noite, até amanhã, equipe!", "Improdutivo"),
    ("Feliz início de semana para todos!", "Improdutivo"),
    ("Quero agradecer pela paciência e apoio de todos.", "Improdutivo"),
    ("Desejo ótimas férias a todos que estarão de recesso.", "Improdutivo"),
    ("Bom dia, que hoje possamos alcançar nossos objetivos com alegria.", "Improdutivo"),
    ("Compartilho uma frase motivacional: 'O impossível é apenas questão de opinião.'", "Improdutivo"),
    ("Parabéns ao colega Roberto pelo tempo de casa completado hoje.", "Improdutivo"),
    ("Desejo uma excelente noite a todos, até amanhã.", "Improdutivo")
]