EXAMPLES = [
    # Produtivo
    ("Preciso de atualização sobre o processo #123, por favor envie o status.", 'Produtivo'),
    ("O sistema está apresentando erro ao gerar relatórios, preciso de ajuda.", 'Produtivo'),
    ("Envio arquivos solicitados em anexo.", 'Produtivo'),
    ("A reunião foi adiada para amanhã no mesmo horário. Não falte, é importante.", 'Produtivo'),
    ("Convocamos todos para a reunião da próxima semana.", 'Produtivo'),
    ("Favor revisar o documento em anexo até sexta-feira.", 'Produtivo'),
    ("Solicito atualização sobre a abertura da conta corporativa iniciada na semana passada.", 'Produtivo'),
    ("Poderiam me enviar o status da análise de crédito referente ao processo #45789?", 'Produtivo'),
    ("Encaminho em anexo o comprovante de pagamento do boleto vencido em 12/09.", 'Produtivo'),
    ("Favor revisar os relatórios financeiros do segundo trimestre.", 'Produtivo'),
    ("Preciso que a equipe confirme a reunião marcada para amanhã às 14h.", 'Produtivo'),
    ("Segue a planilha de fluxo de caixa atualizada.", 'Produtivo'),
    ("Solicito aprovação para a transferência internacional pendente.", 'Produtivo'),
    ("Favor atualizar o cadastro do cliente João Pereira.", 'Produtivo'),
    ("Preciso de retorno sobre a solicitação de estorno enviada na última sexta-feira.", 'Produtivo'),
    ("A auditoria solicitou cópia dos contratos de empréstimo ativos.", 'Produtivo'),
    ("Favor anexar ao sistema os comprovantes fiscais de agosto.", 'Produtivo'),
    ("Estou reenviando os documentos solicitados pela área de compliance.", 'Produtivo'),
    ("Preciso do parecer jurídico sobre a cláusula do contrato de financiamento.", 'Produtivo'),
    ("Encaminho a versão revisada do relatório de riscos.", 'Produtivo'),
    ("Solicitamos apoio para desbloquear o acesso ao sistema de gestão.", 'Produtivo'),
    ("Favor informar o saldo atualizado da conta investimento #99872.", 'Produtivo'),
    ("Necessário confirmar a liquidação da operação de câmbio de ontem.", 'Produtivo'),
    ("Encaminho proposta comercial revisada para análise.", 'Produtivo'),
    ("Favor incluir os novos dados bancários no cadastro do fornecedor.", 'Produtivo'),
    ("Preciso do cronograma atualizado para entrega do projeto X.", 'Produtivo'),
    ("Segue relatório consolidado das despesas do mês.", 'Produtivo'),
    ("Solicito a emissão da nota fiscal referente ao contrato Y.", 'Produtivo'),
    ("Encaminho documentação para abertura de conta PJ.", 'Produtivo'),
    ("Preciso confirmar o agendamento da videoconferência de amanhã.", 'Produtivo'),
    ("Solicito a reemissão do boleto da fatura de setembro.", 'Produtivo'),
    ("Favor encaminhar as informações de contato do responsável pela auditoria.", 'Produtivo'),
    ("Preciso de suporte para corrigir erro na conciliação bancária.", 'Produtivo'),
    ("Encaminho termo de adesão assinado digitalmente.", 'Produtivo'),
    ("Favor revisar os indicadores de performance enviados no dashboard.", 'Produtivo'),
    ("Solicito confirmação da atualização cadastral concluída no sistema.", 'Produtivo'),
    ("Preciso de atualização sobre a análise do contrato de crédito enviado ontem.", 'Produtivo'),
    ("Favor reenviar os relatórios trimestrais para o comitê.", 'Produtivo'),
    ("Solicito desbloqueio imediato da conta PJ #45678.", 'Produtivo'),
    ("Segue em anexo a planilha com as despesas do mês.", 'Produtivo'),
    ("Preciso da confirmação do pagamento da fatura #98231.", 'Produtivo'),
    ("Favor revisar os documentos enviados pelo cliente João Silva.", 'Produtivo'),
    ("Solicito posição sobre a auditoria externa programada para novembro.", 'Produtivo'),
    ("Encaminho os comprovantes fiscais pendentes para análise.", 'Produtivo'),
    ("Necessário confirmar a liquidação da operação de câmbio realizada ontem.", 'Produtivo'),
    ("Preciso de suporte para acesso ao sistema de relatórios.", 'Produtivo'),
    ("Favor revisar os indicadores de performance de setembro.", 'Produtivo'),
    ("Encaminho minuta revisada do contrato de parceria.", 'Produtivo'),
    ("Solicito confirmação da atualização cadastral do cliente.", 'Produtivo'),
    ("Favor agendar reunião com a área de compliance para sexta-feira.", 'Produtivo'),
    ("Preciso que a equipe envie o parecer jurídico até amanhã.", 'Produtivo'),
    ("Encaminho a planilha de fluxo de caixa revisada.", 'Produtivo'),
    ("Solicito aprovação da transferência internacional de 20 mil dólares.", 'Produtivo'),
    ("Preciso de retorno sobre a solicitação de estorno do boleto vencido.", 'Produtivo'),
    ("Favor anexar ao sistema os contratos digitalizados.", 'Produtivo'),
    ("Segue versão final do relatório de riscos corporativos.", 'Produtivo'),
    ("Solicito desbloqueio de acesso do colaborador ao ERP.", 'Produtivo'),
    ("Favor informar o saldo atualizado da conta investimento #12345.", 'Produtivo'),
    ("Encaminho proposta revisada para avaliação da diretoria.", 'Produtivo'),
    ("Preciso da ata da reunião de ontem para registro.", 'Produtivo'),
    ("Solicito emissão da nota fiscal do contrato #897.", 'Produtivo'),
    ("Favor incluir novos dados bancários do fornecedor XPTO.", 'Produtivo'),
    ("Segue relatório consolidado de despesas do trimestre.", 'Produtivo'),
    ("Preciso confirmar agendamento da videoconferência às 15h.", 'Produtivo'),
    ("Encaminho documentação para abertura de conta corrente empresarial.", 'Produtivo'),
    ("Solicito atualização do cronograma do projeto Finance X.", 'Produtivo'),
    ("Preciso de parecer contábil sobre a operação registrada ontem.", 'Produtivo'),
    ("Encaminho termo de adesão assinado eletronicamente.", 'Produtivo'),
    ("Solicito apoio da TI para corrigir erro de conciliação bancária.", 'Produtivo'),
    ("Favor revisar planilha de metas enviada pela área comercial.", 'Produtivo'),
    ("Encaminho comprovante de pagamento referente à fatura #789.", 'Produtivo'),
    ("Preciso que enviem relatório de inadimplência atualizado.", 'Produtivo'),
    ("Solicito aprovação para contratação do serviço externo.", 'Produtivo'),
    ("Favor confirmar recebimento dos documentos de compliance.", 'Produtivo'),
    ("Segue ata revisada da reunião de diretoria.", 'Produtivo'),
    ("Solicito status da análise de crédito do cliente Maria Souza.", 'Produtivo'),
    ("Preciso que revisem os indicadores financeiros de agosto.", 'Produtivo'),
    ("Encaminho contratos revisados para assinatura.", 'Produtivo'),
    ("Solicito inclusão de novo usuário no sistema de gestão.", 'Produtivo'),
    ("Favor enviar relatórios de performance semanal.", 'Produtivo'),
    ("Preciso da aprovação da diretoria para execução do projeto Y.", 'Produtivo'),
    ("Encaminho parecer jurídico solicitado ontem.", 'Produtivo'),
    ("Solicito revisão do processo #99873 no sistema.", 'Produtivo'),
    ("Favor atualizar cadastro do cliente Carlos Eduardo.", 'Produtivo'),
    ("Preciso confirmar a liquidação do contrato de câmbio #4578.", 'Produtivo'),
    ("Encaminho cronograma atualizado do projeto Finance Pro.", 'Produtivo'),
    ("Solicito emissão do boleto de outubro.", 'Produtivo'),
    ("Preciso de orientação sobre cláusula contratual.", 'Produtivo'),
    ("Favor revisar a planilha de riscos operacionais.", 'Produtivo'),
    ("Solicito a consolidação dos resultados financeiros do trimestre.", 'Produtivo'),
    ("Encaminho minuta de aditivo contratual.", 'Produtivo'),
    ("Preciso do relatório de conciliação de ontem.", 'Produtivo'),
    ("Solicito confirmação de recebimento da documentação enviada.", 'Produtivo'),
    ("Favor reemitir nota fiscal referente ao contrato #566.", 'Produtivo'),
    ("Segue documentação do cliente para validação.", 'Produtivo'),
    ("Preciso do detalhamento das despesas de setembro.", 'Produtivo'),
    ("Solicito revisão da política de crédito interna.", 'Produtivo'),
    ("Favor informar prazos de liquidação de operações internacionais.", 'Produtivo'),
    ("Encaminho planilha de contas a pagar atualizada.", 'Produtivo'),
    ("Solicito parecer sobre risco operacional identificado.", 'Produtivo'),
    ("Preciso de relatório consolidado de investimentos.", 'Produtivo'),
    ("Encaminho documentos solicitados pela auditoria externa.", 'Produtivo'),
    ("Favor revisar cálculo de provisão de inadimplência.", 'Produtivo'),
    ("Solicito atualização do sistema com dados de setembro.", 'Produtivo'),
    ("Preciso confirmar agenda de reunião com investidores.", 'Produtivo'),
    ("Encaminho comprovante de TED realizada hoje.", 'Produtivo'),
    ("Solicito aprovação do orçamento para o projeto Z.", 'Produtivo'),
    ("Favor incluir nota explicativa no relatório contábil.", 'Produtivo'),
    ("Preciso confirmar prazos de auditoria.", 'Produtivo'),
    ("Encaminho minuta de contrato revisada.", 'Produtivo'),
    ("Solicito backup do sistema de gestão financeira.", 'Produtivo'),
    ("Favor revisar dados de cadastro do fornecedor XP.", 'Produtivo'),
    ("Preciso do parecer da área fiscal.", 'Produtivo'),
    ("Encaminho ata de reunião para validação.", 'Produtivo'),
    ("Solicito atualização de senha no sistema.", 'Produtivo'),
    ("Favor confirmar recebimento do relatório enviado ontem.", 'Produtivo'),
    ("Preciso que enviem relatório sobre carteira de crédito.", 'Produtivo'),
    ("Encaminho material solicitado pela área de risco.", 'Produtivo'),
    ("Solicito alinhamento com a equipe de auditoria.", 'Produtivo'),
    ("Favor atualizar dados da conta PJ do cliente.", 'Produtivo'),
    ("Preciso confirmar a conclusão do processo cadastral.", 'Produtivo'),
    ("Encaminho proposta comercial finalizada.", 'Produtivo'),
    ("Solicito emissão de extrato consolidado.", 'Produtivo'),
    ("Favor revisar documentação fiscal enviada.", 'Produtivo'),
    ("Preciso do parecer jurídico sobre contrato social.", 'Produtivo'),
    ("Encaminho comprovante de quitação da fatura #112.", 'Produtivo'),
    ("Solicito relatório de riscos de mercado.", 'Produtivo'),
    ("Favor confirmar recebimento do aditivo contratual.", 'Produtivo'),
    ("Preciso da planilha de provisões contábeis atualizada.", 'Produtivo'),
    ("Encaminho dados para atualização no sistema ERP.", 'Produtivo'),
    ("Solicito posição sobre cobrança em aberto.", 'Produtivo'),
    ("Favor revisar relatórios da área de tesouraria.", 'Produtivo'),

    # Improdutivo
    ("Feliz Natal para toda equipe!", 'Improdutivo'),
    ("Obrigado pelo suporte, ótimo trabalho.", 'Improdutivo'),
    ("Parabéns pelo projeto, sucesso a todos.", 'Improdutivo'),
    ("Bom dia, espero que esteja bem!", 'Improdutivo'),
    ("Desejo um excelente final de semana a todos!", 'Improdutivo'),
    ("Feliz aniversário para todos os colegas que comemoram este mês!", 'Improdutivo'),
    ("Desejo um excelente final de semana para toda a equipe.", 'Improdutivo'),
    ("Bom dia! Espero que estejam todos bem.", 'Improdutivo'),
    ("Compartilho uma mensagem de motivação para iniciar a semana.", 'Improdutivo'),
    ("Feliz Natal e um próspero Ano Novo a todos.", 'Improdutivo'),
    ("Parabéns pelo sucesso do time no último evento.", 'Improdutivo'),
    ("Espero que todos aproveitem o feriado prolongado.", 'Improdutivo'),
    ("Compartilhando fotos do happy hour da semana passada.", 'Improdutivo'),
    ("Desejo uma ótima tarde a todos.", 'Improdutivo'),
    ("Envio este email apenas para agradecer pelo excelente trabalho.", 'Improdutivo'),
    ("Parabéns a todos os envolvidos no projeto concluído.", 'Improdutivo'),
    ("Que todos tenham uma semana produtiva e feliz.", 'Improdutivo'),
    ("Desejo uma ótima Páscoa para os colegas.", 'Improdutivo'),
    ("Compartilho artigo de revista sobre finanças pessoais.", 'Improdutivo'),
    ("Envio uma mensagem de agradecimento pela amizade no time.", 'Improdutivo'),
    ("Desejo sorte a todos os participantes da corrida de rua no domingo.", 'Improdutivo'),
    ("Que todos aproveitem bem o dia de sol.", 'Improdutivo'),
    ("Mensagem de bom humor para alegrar a semana.", 'Improdutivo'),
    ("Desejo uma boa viagem ao colega que está saindo de férias.", 'Improdutivo'),
    ("Compartilho um vídeo motivacional interessante.", 'Improdutivo'),
    ("Parabéns à equipe pelo aniversário de 10 anos da empresa.", 'Improdutivo'),
    ("Desejo felicidades aos aniversariantes de outubro.", 'Improdutivo'),
    ("Que todos tenham um ótimo almoço.", 'Improdutivo'),
    ("Compartilhando convite para confraternização de fim de ano.", 'Improdutivo'),
    ("Desejo que todos tenham um ótimo descanso no fim de semana.", 'Improdutivo'),
    ("Compartilho uma piada para animar a manhã.", 'Improdutivo'),
    ("Envio fotos do campeonato de futebol interno.", 'Improdutivo'),
    ("Parabéns pelo excelente clima organizacional alcançado.", 'Improdutivo'),
    ("Desejo a todos boas festas e muita saúde.", 'Improdutivo'),
    ("Apenas passando para cumprimentar todos os colegas.", 'Improdutivo'),
    ("Feliz Ano Novo a todos os colegas!", 'Improdutivo'),
    ("Bom dia! Desejo uma ótima terça-feira.", 'Improdutivo'),
    ("Parabéns pelo ótimo desempenho do time.", 'Improdutivo'),
    ("Espero que aproveitem o feriado prolongado.", 'Improdutivo'),
    ("Envio fotos do happy hour de sexta-feira.", 'Improdutivo'),
    ("Que todos tenham uma semana abençoada.", 'Improdutivo'),
    ("Desejo um excelente final de semana.", 'Improdutivo'),
    ("Parabéns pelo sucesso da festa de confraternização.", 'Improdutivo'),
    ("Compartilho um vídeo motivacional.", 'Improdutivo'),
    ("Bom almoço a todos!", 'Improdutivo'),
    ("Feliz aniversário ao colega João!", 'Improdutivo'),
    ("Desejo muita saúde e paz neste mês.", 'Improdutivo'),
    ("Mensagem de bom humor para alegrar o dia.", 'Improdutivo'),
    ("Parabéns à equipe pelos 20 anos da empresa.", 'Improdutivo'),
    ("Espero que aproveitem bem o dia de sol.", 'Improdutivo'),
    ("Desejo uma Páscoa feliz e cheia de alegria.", 'Improdutivo'),
    ("Compartilho artigo sobre saúde financeira pessoal.", 'Improdutivo'),
    ("Que todos tenham uma ótima tarde!", 'Improdutivo'),
    ("Envio mensagem apenas para agradecer.", 'Improdutivo'),
    ("Parabéns a todos os aniversariantes do mês.", 'Improdutivo'),
    ("Desejo uma ótima viagem ao colega que saiu de férias.", 'Improdutivo'),
    ("Compartilho piada para animar a manhã.", 'Improdutivo'),
    ("Que todos aproveitem o churrasco da sexta.", 'Improdutivo'),
    ("Parabéns pelo clima organizacional positivo.", 'Improdutivo'),
    ("Desejo boas festas e muita felicidade.", 'Improdutivo'),
    ("Bom descanso no feriado a todos.", 'Improdutivo'),
    ("Envio fotos do campeonato de futebol interno.", 'Improdutivo'),
    ("Compartilho mensagem motivacional sobre sucesso.", 'Improdutivo'),
    ("Desejo uma semana iluminada a todos.", 'Improdutivo'),
    ("Parabéns pelo resultado da corrida de rua.", 'Improdutivo'),
    ("Que todos tenham um excelente café da manhã.", 'Improdutivo'),
    ("Feliz Dia das Mães a todos!", 'Improdutivo'),
    ("Compartilho um convite para confraternização.", 'Improdutivo'),
    ("Desejo boa sorte na maratona do próximo domingo.", 'Improdutivo'),
    ("Mensagem de incentivo para a semana.", 'Improdutivo'),
    ("Parabéns pela apresentação no evento externo.", 'Improdutivo'),
    ("Desejo felicidade e harmonia para todos.", 'Improdutivo'),
    ("Bom feriado a todos, aproveitem!", 'Improdutivo'),
    ("Compartilho fotos da festa junina.", 'Improdutivo'),
    ("Desejo paz e sucesso para equipe.", 'Improdutivo'),
    ("Parabéns pelo prêmio recebido pela empresa.", 'Improdutivo'),
    ("Feliz aniversário à colega Maria!", 'Improdutivo'),
    ("Desejo alegria no início desta semana.", 'Improdutivo'),
    ("Envio poema motivacional para reflexão.", 'Improdutivo'),
    ("Parabéns pelo engajamento do time.", 'Improdutivo'),
    ("Bom descanso no fim de semana.", 'Improdutivo'),
    ("Desejo prosperidade a todos neste mês.", 'Improdutivo'),
    ("Feliz Natal e próspero Ano Novo.", 'Improdutivo'),
    ("Que todos aproveitem o feriado.", 'Improdutivo'),
    ("Compartilho vídeo engraçado para animar o dia.", 'Improdutivo'),
    ("Parabéns pelo sucesso no último evento social.", 'Improdutivo'),
    ("Desejo uma sexta-feira abençoada.", 'Improdutivo'),
    ("Bom dia! Apenas passando para cumprimentar.", 'Improdutivo'),
    ("Mensagem positiva para motivar a semana.", 'Improdutivo'),
    ("Parabéns pelo aniversário da empresa.", 'Improdutivo'),
    ("Desejo alegria no feriado prolongado.", 'Improdutivo'),
    ("Compartilho fotos da confraternização anual.", 'Improdutivo'),
    ("Bom final de semana a todos!", 'Improdutivo'),
    ("Desejo felicidade e paz no mês de outubro.", 'Improdutivo'),
    ("Parabéns ao colega pela promoção.", 'Improdutivo'),
    ("Espero que aproveitem o almoço de hoje.", 'Improdutivo'),
    ("Mensagem de amizade para equipe.", 'Improdutivo'),
    ("Desejo uma semana cheia de energia.", 'Improdutivo'),
    ("Feliz aniversário para todos do mês.", 'Improdutivo'),
    ("Compartilho artigo sobre finanças pessoais.", 'Improdutivo'),
    ("Bom dia, equipe! Que seja leve.", 'Improdutivo'),
    ("Parabéns pelo esforço coletivo no projeto.", 'Improdutivo'),
    ("Desejo ótima tarde de descanso.", 'Improdutivo'),
    ("Envio foto do time no café da manhã.", 'Improdutivo'),
    ("Mensagem motivadora para inspirar todos.", 'Improdutivo'),
    ("Desejo boa viagem ao colega.", 'Improdutivo'),
    ("Feliz aniversário à equipe da filial.", 'Improdutivo'),
    ("Bom humor para começar a semana.", 'Improdutivo'),
    ("Parabéns pela vitória do time interno.", 'Improdutivo'),
    ("Desejo um ótimo sábado ensolarado.", 'Improdutivo'),
    ("Envio imagens do passeio da empresa.", 'Improdutivo'),
    ("Mensagem de otimismo para hoje.", 'Improdutivo'),
    ("Desejo sucesso e saúde a todos.", 'Improdutivo'),
    ("Parabéns pelo ótimo trabalho do mês.", 'Improdutivo'),
    ("Feliz Dia dos Pais para todos.", 'Improdutivo'),
    ("Bom descanso merecido a todos.", 'Improdutivo'),
    ("Desejo uma semana produtiva.", 'Improdutivo'),
    ("Compartilho música motivacional.", 'Improdutivo'),
    ("Parabéns à equipe pelo engajamento.", 'Improdutivo'),
    ("Desejo excelente tarde de sol.", 'Improdutivo'),
    ("Envio fotos do time no evento esportivo.", 'Improdutivo'),
    ("Mensagem de gratidão ao grupo.", 'Improdutivo'),
    ("Desejo boas energias no mês novo.", 'Improdutivo'),
    ("Parabéns pelo sucesso no prêmio externo.", 'Improdutivo'),
    ("Bom dia! Que a semana seja ótima.", 'Improdutivo'),
    ("Desejo alegria na confraternização.", 'Improdutivo'),
    ("Compartilho lembrança do último evento social.", 'Improdutivo'),
    ("Parabéns pelos resultados do campeonato.", 'Improdutivo'),
    ("Desejo felicidade a todos sempre.", 'Improdutivo')
]